- docs/view/index.rst
Add initial documentation about themes support, how to create a new one, folder structure and how to use a specific theme inside a controller
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:
> Included initial doc from theme support

- docs/confproject.rst
Add Laravel Valet Driver support
> Laravel Valet Driver for Doc

- CHANGELOG.md
- src/Ubiquity/annotations/TableAnnotation.php
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #39
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:
> small patch for fix [ORM] model Table annotation #39

- src/Ubiquity/controllers/Startup.php
- src/Ubiquity/db/Database.php
- src/Ubiquity/db/providers/AbstractDbWrapper.php
- src/Ubiquity/db/providers/pdo/PDOWrapper.php
- src/Ubiquity/db/traits/DatabaseOperationsTrait.php
- src/Ubiquity/orm/DAO.php
> Adds Db pooling (for Swoole coroutine Mysql)

- src/Ubiquity/utils/http/URequest.php
> updated some docblocks

- .scrutinizer.yml
- src/Ubiquity/controllers/Startup.php
- src/Ubiquity/db/providers/pdo/PDOWrapper.php
- src/Ubiquity/orm/traits/DAOPooling.php
- src/Ubiquity/orm/traits/DAORelationsTrait.php
- src/Ubiquity/utils/http/USession.php
- src/tests/unit/dao/DAOWithApcTest.php
- Fix charset pb in pgsql
- Fix return values
- Update Pooling constructor
> PDO wrapper update

- src/Ubiquity/orm/DAO.php
- src/Ubiquity/orm/bulk/AbstractBulks.php
- src/Ubiquity/orm/bulk/BulkDeletes.php
- src/Ubiquity/orm/bulk/BulkInserts.php
- src/Ubiquity/orm/bulk/BulkUpdates.php
- src/Ubiquity/orm/traits/DAOBulkUpdatesTrait.php
- src/Ubiquity/orm/traits/DAOPooling.php
- src/Ubiquity/orm/traits/DAOUpdatesTrait.php
Add bulk queries for deleting, adding or updating instances
- `DAO::toInsert(object)`, `DAO::toInserts(objects)`
- `DAO::toUpdate(object)`, `DAO::toUpdates(objects)`
- `DAO::toDelete(object)`, `DAO::toDeletes(objects)`
- `DAO::flush()`, `DAO::flushUpdates()`, `DAO::flushDeletes()`, `DAO::flushInserts()`
> Bulk queries

- CHANGELOG.md
- README.md
- src/Ubiquity/core/Framework.php
- src/Ubiquity/orm/DAO.php
- src/Ubiquity/orm/parser/ConditionParser.php
- src/Ubiquity/utils/base/UIntrospection.php
- src/Ubiquity/views/View.php
- src/Ubiquity/views/engine/micro/MicroTemplateEngine.php
- src/Ubiquity/views/engine/micro/TemplateParser.php
> Update to 2.3.2

- src/Ubiquity/cache/traits/ModelsCacheTrait.php
- src/Ubiquity/cache/traits/RouterCacheTrait.php
- src/Ubiquity/controllers/Startup.php
- src/Ubiquity/db/SqlUtils.php
- src/Ubiquity/orm/OrmUtils.php
- src/Ubiquity/orm/bulk/BulkUpdates.php
- src/Ubiquity/orm/traits/DAOBulkUpdatesTrait.php
- src/Ubiquity/orm/traits/DAOCoreTrait.php
- src/Ubiquity/utils/base/UString.php
- src/Ubiquity/utils/http/UCookie.php
- src/Ubiquity/utils/http/URequest.php
- src/Ubiquity/views/View.php
- Adds **warmup** for client servers (Swoole, Workerman...)
- `OrmUtils`light optimization
> Add warmup

- src/Ubiquity/controllers/semantic/MessagesTrait.php
- src/Ubiquity/core/views/main/vFooter.html
- src/Ubiquity/core/views/main/vHeader.html
- clients libraries (jQuery, Semantic) versions
> Update to fomantic 2.8.1

- src/Ubiquity/cache/Preloader.php
- src/Ubiquity/cache/system/ObjectCache.php
- src/Ubiquity/cache/traits/ModelsCacheTrait.php
- src/Ubiquity/controllers/auth/AuthFiles.php
- src/Ubiquity/core/scripts/preloader.php
- src/Ubiquity/utils/base/UArray.php
Add opcache preloading for php 7.4.
> Techempower benchmarks

- src/Ubiquity/orm/DAO.php
- src/Ubiquity/orm/SDAO.php
- src/Ubiquity/orm/core/prepared/DAOPreparedQuery.php
- src/Ubiquity/orm/core/prepared/DAOPreparedQueryAll.php
- src/Ubiquity/orm/core/prepared/DAOPreparedQueryById.php
- src/Ubiquity/orm/core/prepared/DAOPreparedQueryOne.php
- src/Ubiquity/orm/traits/DAOCoreTrait.php
- src/Ubiquity/orm/traits/DAOPreparedTrait.php
- src/Ubiquity/orm/traits/DAORelationsAssignmentsTrait.php
- src/Ubiquity/orm/traits/DAORelationsTrait.php
Adds the ability to prepare data queries (getById, getOne, getAll) with asynchronous platforms
> Add prepared DAO queries

- CHANGELOG.md
- src/Ubiquity/controllers/crud/CRUDController.php
- src/Ubiquity/controllers/crud/CRUDControllerUtilitiesTrait.php
- src/Ubiquity/controllers/crud/CRUDHelper.php
- src/Ubiquity/controllers/crud/viewers/traits/FormModelViewerTrait.php
- src/Ubiquity/db/Database.php
- src/Ubiquity/db/SqlUtils.php
- src/Ubiquity/db/providers/AbstractDbWrapper.php
- src/Ubiquity/db/providers/pdo/PDOWrapper.php
- src/Ubiquity/db/providers/pdo/drivers/AbstractDriverMetaDatas.php
- src/Ubiquity/db/providers/pdo/drivers/MysqlDriverMetas.php
- src/Ubiquity/db/providers/pdo/drivers/PgsqlDriverMetas.php
- src/Ubiquity/db/providers/pdo/drivers/SqliteDriverMetas.php
- src/Ubiquity/db/traits/DatabaseMetadatas.php
- src/Ubiquity/db/traits/DatabaseOperationsTrait.php
- src/Ubiquity/orm/DAO.php
- src/Ubiquity/orm/core/prepared/DAOPreparedQueryAll.php
- src/Ubiquity/orm/core/prepared/DAOPreparedQueryById.php
- src/Ubiquity/orm/parser/ManyToManyParser.php
- src/Ubiquity/orm/traits/DAOCoreTrait.php
- src/Ubiquity/orm/traits/DAORelationsPrepareTrait.php
- src/Ubiquity/orm/traits/DAORelationsTrait.php
- src/Ubiquity/orm/traits/DAOUQueries.php
- src/Ubiquity/orm/traits/DAOUpdatesTrait.php
- src/Ubiquity/orm/traits/OrmUtilsRelationsTrait.php
Add PostgreSQL driver meta class.
Fixes https://github.com/phpMv/ubiquity/issues/98
> Add pdo driver metas

- CHANGELOG.md
- src/Ubiquity/db/providers/pdo/drivers/SqliteDriverMetas.php
Add SQLite driver meta class.
Fixes https://github.com/phpMv/ubiquity/issues/90
> Add SQLite pdo driver Support (#101)

- src/Ubiquity/orm/core/prepared/DAOPreparedQuery.php
- src/Ubiquity/orm/core/prepared/DAOPreparedQueryAll.php
- src/Ubiquity/orm/core/prepared/DAOPreparedQueryById.php
- src/Ubiquity/orm/traits/DAOPreparedTrait.php
Add additional fields in prepared queries.
Fixes https://github.com/phpMv/ubiquity/issues/83
> Select add fields

- docs/controller/controllers.rst
- docs/controller/router.rst
- docs/extra/dependencies.rst
- src/Ubiquity/cache/CacheManager.php
- src/Ubiquity/orm/core/prepared/DAOPreparedQuery.php
- src/Ubiquity/orm/core/prepared/DAOPreparedQueryAll.php
- src/Ubiquity/orm/core/prepared/DAOPreparedQueryById.php
- src/Ubiquity/orm/traits/DAOCoreTrait.php
Fix the problems on the Column annotation.
Adds annotation integration for all HTTP methods.
Fixes # (https://github.com/phpMv/ubiquity/issues/117, https://github.com/phpMv/ubiquity/issues/116)
> Fix column annot pbs

- src/Ubiquity/db/providers/AbstractDbWrapper.php
- src/Ubiquity/db/providers/pdo/PDOWrapper.php
- src/Ubiquity/db/traits/DatabaseOperationsTrait.php
- src/Ubiquity/orm/SDAO.php
- src/Ubiquity/orm/core/prepared/DAOPreparedQuery.php
- src/Ubiquity/orm/core/prepared/DAOPreparedQueryAll.php
- src/Ubiquity/orm/core/prepared/DAOPreparedQueryById.php
- src/Ubiquity/orm/core/prepared/DAOPreparedQueryOne.php
- src/Ubiquity/orm/parser/ConditionParser.php
- src/Ubiquity/orm/traits/DAOCoreTrait.php
DAO prepared queries optimization => add prepare statements in DAOPreparedQueries
> Dao async opt

- src/Ubiquity/controllers/Startup.php
Just noticed some typos when I was testing out the framework
> Fix some typos

- src/Ubiquity/controllers/StartupAsync.php
- Async startup optimization: memorization of the parameters corresponding to an url (controller, action, params, requested method).
> Async Startup light opt

- src/Ubiquity/annotations/AnnotationsEngineInterface.php
- src/Ubiquity/annotations/BaseAnnotationTrait.php
- src/Ubiquity/cache/parser/ControllerParser.php
- src/Ubiquity/cache/parser/RestControllerParser.php
- src/Ubiquity/cache/traits/DevCacheTrait.php
- src/Ubiquity/cache/traits/DevRouterCacheTrait.php
- src/Ubiquity/cache/traits/ModelsCacheTrait.php
- src/Ubiquity/contents/validation/ValidationModelGenerator.php
- src/Ubiquity/contents/validation/ValidationModelParser.php
- src/Ubiquity/controllers/di/DiControllerParser.php
- src/Ubiquity/orm/parser/Reflexion.php
- src/Ubiquity/orm/parser/ReflexionFieldsTrait.php
- src/Ubiquity/utils/base/traits/UArrayAsTrait.php
> Php8 attributes

- docs/index.rst
> fix typo in index.rst

- docs/view/index.rst
- src/Ubiquity/assets/AssetsManager.php
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:
> 188 asset manager img

- src/Ubiquity/cache/CacheManager.php
- src/Ubiquity/cache/traits/DevCacheTrait.php
- src/Ubiquity/cache/traits/DevRouterCacheTrait.php
- src/Ubiquity/cache/traits/ModelsCacheTrait.php
- src/Ubiquity/cache/traits/RestCacheTrait.php
- src/Ubiquity/cache/traits/RouterCacheTrait.php
- src/Ubiquity/controllers/semantic/MessagesTrait.php
- src/Ubiquity/controllers/traits/StartupConfigTrait.php
- src/Ubiquity/core/Framework.php
- src/Ubiquity/core/views/main/vFooter.html
- src/Ubiquity/core/views/main/vHeader.html
- src/Ubiquity/exceptions/InvalidCodeException.php
- src/Ubiquity/utils/base/traits/UArrayAsTrait.php
- src/tests/unit/core/FrameworkTest.php
Introduce env vars usage in config files.
> 199 rfc config add env variables and profiles to config
